### ISSUE TITLE
Horizontal and vertical scroll bars appear after dragging in an extension

### ISSUE THREAD

**Issue by python-dy** [FsuLauncherComp/BootstrapTableau#8]
Hello,I'm having the following problem using the TabCSS extension in Tableau 2022.2,When I drag the TabCSS into the dashboard, scroll bars appear both horizontally and vertically.
![image](https://user-images.githubusercontent.com/74307598/184849778-ded0e240-25f8-4c97-a0b2-4b2ca2864e15.png)
Then I try to add the worksheet and follow the instructions in the document, but the background position does not correspond to the result.
![image](https://user-images.githubusercontent.com/74307598/184850919-9f2bde5b-fa66-45bb-9cfd-85649bb1bfed.png)
I don't know where is the problem,thank you for your help!

**Comment by python-dy** [comment]
The scroll bar can't be clicked and the zoom-in extension scroll bar still exists

**Comment by zakovichr** [comment]
I have seen this error reported before during internal tests.

From my understanding, this appears to be related to certain Windows machines depending on screen resolutions and how Tableau renders the Extension frame.

I am trying to identify which specific Windows based machines cause this and ways to mitigate the issue.

**Comment by python-dy** [comment]
Thank you for your answer, indeed, I'm using Windows 11 with a monitor resolution of 2520x1680 and a scaling of 150%, unfortunately I can't use this very useful extension now, thanks again. At the same time, I will continue to pay attention to the dynamics of this extension.^^

**Comment by zakovichr** [comment]
Apologies, this appears to be related to how Tableau renders the extension browser in Desktop. Hopefully it is something they can resolve quickly.

In the meantime, one workaround can be to safelist the extension on server, publish the workbook, and then use the extension in web edit mode. This workaround isn't the best, but does work

**Comment by zakovichr** [comment]
Some good news!

Another user reported a potential solution that appears to be working for them.

On a Windows PC, if you close Tableau, change your scaling to 100%, and then re-open Tableau this extension should properly render.

**Comment by python-dy** [comment]
> Some good news!
> 
> Another user reported a potential solution that appears to be working for them.
> 
> On a Windows PC, if you close Tableau, change your scaling to 100%, and then re-open Tableau this extension should properly render.

Really good news, changing the zoom to 100% did fix the problem, thanks a lot
